version: '3.8'

services:
  mywebsite:
    image: mysite2
    container_name: mywebsite
    ports: 
      - 8080:80
    networks:
      - internalnetwork
    volumes:
      - type: volume
        source: websitevolume
        target: /var/www/site


networks:
  internalnetwork:
    driver: bridge

volumes:
  websitevolume:
    external: true
